/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mahata' at '1/11/16 10:44 PM' with Gradle 2.10
 *
 * @author mahata, @date 1/11/16 10:44 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
